# Generated by Django 2.1.2 on 2018-10-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabang', '0002_auto_20181028_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nama',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
