# Generated by Django 2.1.2 on 2018-10-31 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabang', '0003_auto_20181031_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ip',
        ),
    ]
