# Generated by Django 2.1.2 on 2018-10-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabang', '0004_remove_customer_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ip',
            field=models.CharField(default='', max_length=100),
        ),
    ]
